<a href="https://colab.research.google.com/github/milan-jani/AI-Works/blob/main/Codes/Collaborative_Filtering_based_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Collaborative Filtering based recommendation system

In [4]:
import pandas as pd
import numpy as numpy
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
ratings=pd.read_csv("ratings.csv")

In [6]:
user_item=ratings.pivot_table(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)


In [7]:
#similarity in-between users
user_sim=cosine_similarity(user_item)
user_sim_df=pd.DataFrame(
    user_sim,
    index=user_item.index,
    columns=user_item.index
  )

In [8]:
print(user_sim)
print("----------")
print(user_item)

[[1.         0.02728287 0.05972026 ... 0.29109737 0.09357193 0.14532081]
 [0.02728287 1.         0.         ... 0.04621095 0.0275654  0.10242675]
 [0.05972026 0.         1.         ... 0.02112846 0.         0.03211875]
 ...
 [0.29109737 0.04621095 0.02112846 ... 1.         0.12199271 0.32205486]
 [0.09357193 0.0275654  0.         ... 0.12199271 1.         0.05322546]
 [0.14532081 0.10242675 0.03211875 ... 0.32205486 0.05322546 1.        ]]
----------
movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     